# frozen_string_literal: true

require "bundler/gem_tasks"
require "rake/testtask"

Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.libs << "lib"
  t.test_files = FileList["test/**/*_test.rb"]
end

require "rubocop/rake_task"

RuboCop::RakeTask.new

task :protoc do
  sh 'protoc --proto_path=../xhummingbird_server/protos --ruby_out=lib/xhummingbird/protos ../xhummingbird_server/protos/*.proto'
end

task default: %i[test rubocop]
