# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("event.proto", :syntax => :proto3) do
    add_message "xhummingbird.Event" do
      optional :level, :uint32, 1
      optional :title, :string, 2
      optional :message, :string, 3
      repeated :trace, :string, 4
      map :tags, :string, :string, 5
      optional :timestamp, :message, 6, "google.protobuf.Timestamp"
    end
  end
end

module Xhummingbird
  Event = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xhummingbird.Event").msgclass
end
